name: Android CI

on:
    push:
        paths-ignore:
            - '**.md'
            - '**.txt'
            - '.github/**'
            - '.idea/**'
            - '!.github/workflows/**'
    pull_request:
    workflow_dispatch:

jobs:
    build:
        name: Build debug APK
        runs-on: ubuntu-latest
        steps:
            - name: Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.12.1
              with:
                  access_token: ${{ github.token }}

            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                  java-version: 17
                  distribution: 'temurin'

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v3

            - name: Grant Permissions for Gradle
              run: chmod +x gradlew

            - name: Build debug APK
              id: build
              run: ./gradlew assembleDebug

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              if: ${{ !github.head_ref }}
              with:
                  name: apk-debug
                  path: app/build/outputs/apk/debug/app-debug.apk